name: Deploy Helsemelding Kafka Manager to dev
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    name: "Deploy Helsemelding Kafka Manager to dev"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: "Deploy to dev-gcp"
        uses: "nais/deploy/actions/deploy@v2"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "dev-gcp"
          "RESOURCE": ".nais/helsemelding-kafka-manager-dev.yaml"
